spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://193.112.33.53:3306/cjl
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml