spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bookstore
    username: root
    password: cjl19980516.
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true