spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://193.112.33.53:3306/cjl
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

mybatis:
    type:
      aliases:
        package: com.example.BookStore.model
    mapper:
      locations: classpath:mapper/*.xml
      mappers: com.example.demo.utils.MyMapper
      not-empty: false
      identity: MYSQL

pagehelper:
    helperDialect: mysql
    pagehelper: true
    supportMethodsArguments: true
    params: count=countSql


